#!/usr/bin/env bash
# ==============================================================================
# UKE Config Generator v6.2.2
# ==============================================================================
set -euo pipefail
source "$(dirname "$0")/../lib/core.sh"

# ==============================================================================
# SKHD Generator
# ==============================================================================
gen_skhd() {
    local out="$UKE_GEN/skhd/skhdrc"
    mkdir -p "$(dirname "$out")"
    
    log_info "Generating skhd config..."
    
    cat > "$out" << 'EOF'
# ==============================================================================
# SKHD CONFIG - AUTO-GENERATED BY UKE
# ==============================================================================

# ─────────────────────────────────────────────────────────────────────────────
# Smart Focus & Utilities
# ─────────────────────────────────────────────────────────────────────────────
cmd - escape : yabai -m window --focus mouse
alt - escape : /usr/bin/shortcuts run 'ToggleKeyboard'

# ─────────────────────────────────────────────────────────────────────────────
# Window Focus Navigation (PRIMARY: Cmd + hjkl)
# ─────────────────────────────────────────────────────────────────────────────
cmd - h : yabai -m window --focus west
cmd - j : yabai -m window --focus south
cmd - k : yabai -m window --focus north
cmd - l : yabai -m window --focus east

# ─────────────────────────────────────────────────────────────────────────────
# Window Movement (PRIMARY + SHIFT: Cmd+Shift + hjkl)
# ─────────────────────────────────────────────────────────────────────────────
cmd + shift - h : yabai -m window --warp west
cmd + shift - j : yabai -m window --warp south
cmd + shift - k : yabai -m window --warp north
cmd + shift - l : yabai -m window --warp east

# ─────────────────────────────────────────────────────────────────────────────
# Window Resizing (TERTIARY: Alt+Shift + hjkl)
# ─────────────────────────────────────────────────────────────────────────────
alt + shift - h : yabai -m window --resize left:-50:0
alt + shift - j : yabai -m window --resize bottom:0:50
alt + shift - k : yabai -m window --resize top:0:-50
alt + shift - l : yabai -m window --resize right:50:0

# ─────────────────────────────────────────────────────────────────────────────
# Launch Terminal
# ─────────────────────────────────────────────────────────────────────────────
cmd - return : open -a WezTerm

# ─────────────────────────────────────────────────────────────────────────────
# Window Controls
# ─────────────────────────────────────────────────────────────────────────────
cmd + shift - f : yabai -m window --toggle zoom-fullscreen
cmd + shift - space : yabai -m window --toggle float
cmd + shift - 0x2A : yabai -m window --toggle split

# ─────────────────────────────────────────────────────────────────────────────
# Advanced Layout Controls
# ─────────────────────────────────────────────────────────────────────────────
cmd + ctrl - s : yabai -m window --insert stack
cmd + shift - r : yabai -m space --rotate 90
cmd + shift - x : yabai -m space --mirror x-axis
cmd + shift - y : yabai -m space --mirror y-axis
cmd + shift - b : yabai -m space --balance
cmd + ctrl - t : yabai -m space --layout $(yabai -m query --spaces --space | jq -r 'if .type == "bsp" then "stack" else "bsp" end')

# ─────────────────────────────────────────────────────────────────────────────
# Workspace Navigation (PRIMARY + Number)
# ─────────────────────────────────────────────────────────────────────────────
cmd - 1 : yabai -m space --focus 1
cmd - 2 : yabai -m space --focus 2
cmd - 3 : yabai -m space --focus 3
cmd - 4 : yabai -m space --focus 4
cmd - 5 : yabai -m space --focus 5
cmd - 6 : yabai -m space --focus 6
cmd - 7 : yabai -m space --focus 7
cmd - 8 : yabai -m space --focus 8
cmd - 9 : yabai -m space --focus 9
cmd - 0x1D : yabai -m space --focus 10
cmd - 0x21 : yabai -m space --focus prev
cmd - 0x1E : yabai -m space --focus next

# ─────────────────────────────────────────────────────────────────────────────
# Move Window to Workspace (PRIMARY + SHIFT + Number)
# ─────────────────────────────────────────────────────────────────────────────
cmd + shift - 1 : yabai -m window --space 1 --focus
cmd + shift - 2 : yabai -m window --space 2 --focus
cmd + shift - 3 : yabai -m window --space 3 --focus
cmd + shift - 4 : yabai -m window --space 4 --focus
cmd + shift - 5 : yabai -m window --space 5 --focus
cmd + shift - 6 : yabai -m window --space 6 --focus
cmd + shift - 7 : yabai -m window --space 7 --focus
cmd + shift - 8 : yabai -m window --space 8 --focus
cmd + shift - 9 : yabai -m window --space 9 --focus
cmd + shift - 0x1D : yabai -m window --space 10 --focus

# ─────────────────────────────────────────────────────────────────────────────
# Gather Windows (Cmd + `)
# ─────────────────────────────────────────────────────────────────────────────
# [cite_start]Note: 0x32 is the keycode for Grave (`)[cite: 668].
cmd - 0x32 : $HOME/.local/bin/uke-gather

# ─────────────────────────────────────────────────────────────────────────────
# Quick App Launchers (TERTIARY: Cmd+Alt)
# ─────────────────────────────────────────────────────────────────────────────
cmd + alt - b : open -a 'Brave Browser'
cmd + alt - o : open -a Obsidian
cmd + alt - c : open -a Code
cmd + alt - r : open -a Raindrop.io
cmd + alt - m : open -a Spotify
cmd + alt - t : open -a WezTerm

# ─────────────────────────────────────────────────────────────────────────────
# Bunches (BUNCH: Cmd+Ctrl)
# ─────────────────────────────────────────────────────────────────────────────
cmd + ctrl - 1 : $HOME/.local/bin/uke-bunch study
cmd + ctrl - 2 : $HOME/.local/bin/uke-bunch guitar
cmd + ctrl - 3 : $HOME/.local/bin/uke-bunch coding
cmd + ctrl - 4 : $HOME/.local/bin/uke-bunch email
cmd + ctrl - 5 : $HOME/.local/bin/uke-bunch reading

# ─────────────────────────────────────────────────────────────────────────────
# Scratchpads (Cmd + Shift + `)
# ─────────────────────────────────────────────────────────────────────────────
cmd + shift - 0x32 : $HOME/.local/bin/uke-scratchpad terminal
cmd + alt - n : $HOME/.local/bin/uke-scratchpad notes

# ─────────────────────────────────────────────────────────────────────────────
# Session Management
# ─────────────────────────────────────────────────────────────────────────────
cmd + ctrl - s : $HOME/.local/bin/uke-session quick-save
cmd + ctrl + shift - s : $HOME/.local/bin/uke-session quick-restore
EOF

    ok "Generated: $out"
}

# ==============================================================================
# YABAI Generator
# ==============================================================================
gen_yabai() {
    local out="$UKE_GEN/yabai/yabairc"
    mkdir -p "$(dirname "$out")"
    
    log_info "Generating yabai config..."
    
    # Header and basic config
    cat > "$out" << 'EOF'
#!/usr/bin/env sh
# ==============================================================================
# YABAI CONFIG - AUTO-GENERATED BY UKE
# ==============================================================================

# Load Scripting Addition
sudo yabai --load-sa

# Layout Configuration
yabai -m config layout bsp
yabai -m config window_placement second_child
yabai -m config top_padding    4
yabai -m config bottom_padding 4
yabai -m config left_padding   4
yabai -m config right_padding  4
yabai -m config window_gap     4

# Mouse Configuration
yabai -m config mouse_follows_focus off
yabai -m config focus_follows_mouse off
yabai -m config mouse_modifier alt
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize

# Window Behavior
yabai -m config split_ratio 0.50
yabai -m config auto_balance off

# Window Borders
pkill -x borders 2>/dev/null || true
borders width=3 active_color=0xff88c0d0 inactive_color=0xff3b4252 &

# Opacity
yabai -m config window_opacity off
yabai -m rule --add app="^WezTerm$" opacity=0.92
yabai -m rule --add app="^Alacritty$" opacity=0.92
yabai -m rule --add app="^iTerm2$" opacity=0.92
yabai -m rule --add app="^Terminal$" opacity=0.95

EOF

    # Window Rules
    cat >> "$out" << 'EOF'
# ==============================================================================
# WINDOW RULES
# ==============================================================================
EOF

    local rule_count
    rule_count=$(yq -r '.window_rules | length' "$UKE_CONFIG/registry.yaml" 2>/dev/null || echo "0")
    
    if [[ "$rule_count" -gt 0 ]]; then
        for i in $(seq 0 $((rule_count - 1))); do
            local app title float center sticky opacity topmost
            
            app=$(yq -r ".window_rules[$i].match.app | select(. != null)" "$UKE_CONFIG/registry.yaml" 2>/dev/null)
            title=$(yq -r ".window_rules[$i].match.title | select(. != null)" "$UKE_CONFIG/registry.yaml" 2>/dev/null)
            float=$(yq -r ".window_rules[$i].float | select(. != null)" "$UKE_CONFIG/registry.yaml" 2>/dev/null)
            center=$(yq -r ".window_rules[$i].center | select(. != null)" "$UKE_CONFIG/registry.yaml" 2>/dev/null)
            sticky=$(yq -r ".window_rules[$i].sticky | select(. != null)" "$UKE_CONFIG/registry.yaml" 2>/dev/null)
            opacity=$(yq -r ".window_rules[$i].opacity | select(. != null)" "$UKE_CONFIG/registry.yaml" 2>/dev/null)
            topmost=$(yq -r ".window_rules[$i].topmost | select(. != null)" "$UKE_CONFIG/registry.yaml" 2>/dev/null)
            
            local rule_opts=""
            [[ "$float" == "true" ]] && rule_opts="$rule_opts manage=off"
            [[ "$sticky" == "true" ]] && rule_opts="$rule_opts sticky=on"
            [[ -n "$opacity" ]] && rule_opts="$rule_opts opacity=$opacity"
            [[ "$topmost" == "true" ]] && rule_opts="$rule_opts layer=above"
            
            if [[ -n "$rule_opts" ]]; then
                if [[ -n "$app" && -n "$title" ]]; then
                    echo "yabai -m rule --add app=\"^${app}$\" title=\"${title}\"$rule_opts" >> "$out"
                elif [[ -n "$app" ]]; then
                    echo "yabai -m rule --add app=\"^${app}$\"$rule_opts" >> "$out"
                elif [[ -n "$title" ]]; then
                    echo "yabai -m rule --add title=\"${title}\"$rule_opts" >> "$out"
                fi
            fi
        done
    fi
    echo "" >> "$out"

    # Workspace App Assignments
    cat >> "$out" << 'EOF'
# ==============================================================================
# WORKSPACE ASSIGNMENTS
# ==============================================================================
EOF

    for ws in $(yq -r '.workspaces | keys | .[]' "$UKE_CONFIG/registry.yaml" 2>/dev/null); do
        local apps
        apps=$(yq -r ".workspaces.${ws}.apps | .[]?" "$UKE_CONFIG/registry.yaml" 2>/dev/null)
        [[ -z "$apps" ]] && continue
        
        echo "" >> "$out"
        echo "# Space $ws" >> "$out"
        
        for app_key in $apps; do
            local app_name
            app_name=$(yq -r ".apps.${app_key}.macos | select(. != null)" "$UKE_CONFIG/registry.yaml" 2>/dev/null)
            [[ -z "$app_name" ]] && continue
            echo "yabai -m rule --add app=\"^${app_name}$\" space=^${ws}" >> "$out"
        done
    done

    # Monitor Assignments
    local monitors_enabled
    monitors_enabled=$(yq -r '.monitors.enabled | select(. != null)' "$UKE_CONFIG/registry.yaml" 2>/dev/null)
    
    if [[ "$monitors_enabled" == "true" ]]; then
        cat >> "$out" << 'EOF'

# ==============================================================================
# MONITOR ASSIGNMENTS
# ==============================================================================
EOF
        local display_count
        display_count=$(yq -r '.monitors.displays | length' "$UKE_CONFIG/registry.yaml" 2>/dev/null || echo "0")
        
        for d in $(seq 0 $((display_count - 1))); do
            local display_index
            display_index=$(yq -r ".monitors.displays[$d].index | select(. != null)" "$UKE_CONFIG/registry.yaml" 2>/dev/null)
            
            local ws_list
            ws_list=$(yq -r ".monitors.displays[$d].workspaces | .[]?" "$UKE_CONFIG/registry.yaml" 2>/dev/null)
            
            for ws in $ws_list; do
                echo "yabai -m space $ws --display $display_index 2>/dev/null || true" >> "$out"
            done
        done
    fi

    # Catch-all rule
    cat >> "$out" << 'EOF'

# Catch-all
EOF
    local all_apps=""
    for ws in $(yq -r '.workspaces | keys | .[]' "$UKE_CONFIG/registry.yaml" 2>/dev/null); do
        for app_key in $(yq -r ".workspaces.${ws}.apps | .[]?" "$UKE_CONFIG/registry.yaml" 2>/dev/null); do
            local app_name
            app_name=$(yq -r ".apps.${app_key}.macos | select(. != null)" "$UKE_CONFIG/registry.yaml" 2>/dev/null)
            [[ -z "$app_name" ]] && continue
            [[ -n "$all_apps" ]] && all_apps="$all_apps|"
            all_apps="$all_apps$app_name"
        done
    done
    
    if [[ -n "$all_apps" ]]; then
        echo "yabai -m rule --add app!=\"^($all_apps)$\" space=^4" >> "$out"
    fi

    cat >> "$out" << 'EOF'
echo "yabai: Configuration loaded"
EOF
    chmod +x "$out"
    ok "Generated: $out"
}

# ==============================================================================
# Hyprland Generator
# ==============================================================================
gen_hyprland() {
    local out="$UKE_GEN/hyprland/hyprland.conf"
    mkdir -p "$(dirname "$out")"
    log_info "Generating Hyprland config..."
    echo "# Hyprland Config Generated by UKE" > "$out"
    ok "Generated: $out"
}

# ==============================================================================
# Gather Script Generator
# ==============================================================================
gen_gather() {
    local out="$UKE_BIN/uke-gather"
    mkdir -p "$(dirname "$out")"

    log_info "Generating uke-gather..."
    
    # CRITICAL FIX: Add symlink resolution logic here
    cat > "$out" << 'HEADER'
#!/usr/bin/env bash
set -euo pipefail

# Resolve symlink to find true source location
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do
  DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
done
SCRIPT_DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
export UKE_ROOT="${SCRIPT_DIR%/bin}"

source "$UKE_ROOT/lib/core.sh"
require_cmd jq yq

gather_macos() {
    local current_space
    current_space=$(yabai -m query --spaces --space | jq -r '.index')
    log_info "Gathering windows for space $current_space..."
    
    case $current_space in
HEADER

    for ws in $(yq -r '.workspaces | keys | .[]' "$UKE_CONFIG/registry.yaml"); do
        local apps=$(yq -r ".workspaces.${ws}.apps | .[]?" "$UKE_CONFIG/registry.yaml" 2>/dev/null)
        [[ -z "$apps" ]] && continue
        
        local selector=""
        for app_key in $apps; do
            local app_name=$(yq -r ".apps.${app_key}.macos | select(. != null)" "$UKE_CONFIG/registry.yaml" 2>/dev/null)
            [[ -z "$app_name" ]] && continue
            [[ -n "$selector" ]] && selector="$selector or "
            selector="${selector}.app == \"$app_name\""
        done
        
        [[ -z "$selector" ]] && continue
        
        cat >> "$out" << EOF
        $ws)
            yabai -m query --windows | jq -r '.[] | select($selector) | .id' | \
                xargs -I {} yabai -m window {} --space $ws 2>/dev/null || true
            ;;
EOF
    done
    
    cat >> "$out" << 'FOOTER'
        *)
            log_info "No gather action for space $current_space"
            ;;
    esac
    ok "Windows gathered"
}

gather_linux() {
    log_warn "Linux gather logic is currently a stub."
}

is_macos && gather_macos || gather_linux
FOOTER

    chmod +x "$out"
    ok "Generated: $out"
}

# ==============================================================================
# Main
# ==============================================================================
gen_all() {
    log_info "Generating all configs..."
    if is_macos; then
        gen_skhd
        gen_yabai
    else
        gen_hyprland
    fi
    gen_gather
    ok "All configs generated"
}

case "${1:-all}" in
    skhd)     gen_skhd ;;
    yabai)    gen_yabai ;;
    hyprland) gen_hyprland ;;
    gather)   gen_gather ;;
    all)      gen_all ;;
    *)        log_fatal "Unknown target: $1" ;;
esac