#!/usr/bin/env bash
# ==============================================================================
# UKE Config Generator v6.2.2
# ==============================================================================
set -euo pipefail
source "$(dirname "$0")/../lib/core.sh"

# ==============================================================================
# SKHD Generator
# ==============================================================================
gen_skhd() {
    local out="$UKE_GEN/skhd/skhdrc"
    mkdir -p "$(dirname "$out")"
    
    log_info "Generating skhd config..."
    
    cat > "$out" << 'EOF'
# ==============================================================================
# SKHD CONFIG - AUTO-GENERATED BY UKE
# ==============================================================================

# ... (Standard navigation bindings) ...
cmd - h : yabai -m window --focus west
cmd - j : yabai -m window --focus south
cmd - k : yabai -m window --focus north
cmd - l : yabai -m window --focus east

cmd + shift - h : yabai -m window --warp west
cmd + shift - j : yabai -m window --warp south
cmd + shift - k : yabai -m window --warp north
cmd + shift - l : yabai -m window --warp east

alt + shift - h : yabai -m window --resize left:-50:0
alt + shift - j : yabai -m window --resize bottom:0:50
alt + shift - k : yabai -m window --resize top:0:-50
alt + shift - l : yabai -m window --resize right:50:0

cmd - return : open -a WezTerm
cmd + shift - f : yabai -m window --toggle zoom-fullscreen
cmd + shift - space : yabai -m window --toggle float
cmd + shift - 0x2A : yabai -m window --toggle split

# Workspace Navigation
cmd - 1 : yabai -m space --focus 1
cmd - 2 : yabai -m space --focus 2
cmd - 3 : yabai -m space --focus 3
cmd - 4 : yabai -m space --focus 4
cmd - 5 : yabai -m space --focus 5
cmd - 6 : yabai -m space --focus 6
cmd - 7 : yabai -m space --focus 7
cmd - 8 : yabai -m space --focus 8
cmd - 9 : yabai -m space --focus 9
cmd - 0x1D : yabai -m space --focus 10
cmd - 0x21 : yabai -m space --focus prev
cmd - 0x1E : yabai -m space --focus next

# Move Window
cmd + shift - 1 : yabai -m window --space 1 --focus
cmd + shift - 2 : yabai -m window --space 2 --focus
cmd + shift - 3 : yabai -m window --space 3 --focus
cmd + shift - 4 : yabai -m window --space 4 --focus
cmd + shift - 5 : yabai -m window --space 5 --focus
cmd + shift - 6 : yabai -m window --space 6 --focus
cmd + shift - 7 : yabai -m window --space 7 --focus
cmd + shift - 8 : yabai -m window --space 8 --focus
cmd + shift - 9 : yabai -m window --space 9 --focus
cmd + shift - 0x1D : yabai -m window --space 10 --focus

# ─────────────────────────────────────────────────────────────────────────────
# Gather Windows (Cmd + `)
# ─────────────────────────────────────────────────────────────────────────────
cmd - 0x32 : $HOME/.local/bin/uke-gather

# ─────────────────────────────────────────────────────────────────────────────
# Quick App Launchers (TERTIARY: Cmd+Alt)
# ─────────────────────────────────────────────────────────────────────────────
cmd + alt - b : open -a 'Brave Browser'
cmd + alt - o : open -a Obsidian
cmd + alt - c : open -a Code
cmd + alt - r : open -a Raindrop.io
cmd + alt - m : open -a Spotify
cmd + alt - t : open -a WezTerm

# ─────────────────────────────────────────────────────────────────────────────
# Bunches (BUNCH: Cmd+Ctrl)
# ─────────────────────────────────────────────────────────────────────────────
cmd + ctrl - 1 : $HOME/.local/bin/uke-bunch study
cmd + ctrl - 2 : $HOME/.local/bin/uke-bunch guitar
cmd + ctrl - 3 : $HOME/.local/bin/uke-bunch coding
cmd + ctrl - 4 : $HOME/.local/bin/uke-bunch email
cmd + ctrl - 5 : $HOME/.local/bin/uke-bunch reading

# ─────────────────────────────────────────────────────────────────────────────
# Scratchpads (Cmd + Shift + `)
# ─────────────────────────────────────────────────────────────────────────────
cmd + shift - 0x32 : $HOME/.local/bin/uke-scratchpad terminal
cmd + alt - n : $HOME/.local/bin/uke-scratchpad notes

# ─────────────────────────────────────────────────────────────────────────────
# Session Management
# ─────────────────────────────────────────────────────────────────────────────
cmd + ctrl - s : $HOME/.local/bin/uke-session quick-save
cmd + ctrl + shift - s : $HOME/.local/bin/uke-session quick-restore
EOF

    ok "Generated: $out"
}

# (Keep gen_yabai, gen_hyprland, and gen_gather exactly as they were in the previous step)
# ...