#!/usr/bin/env bash
# ==============================================================================
# UKE Config Generator v6.1
# ==============================================================================
set -euo pipefail
source "$(dirname "$0")/../lib/core.sh"

# Note: This generator creates static configs. For reliable operation,
# the generated files are the source of truth once created.

# ==============================================================================
# SKHD Generator
# ==============================================================================
gen_skhd() {
    local out="$UKE_GEN/skhd/skhdrc"
    mkdir -p "$(dirname "$out")"
    
    log_info "Generating skhd config..."
    
    cat > "$out" << 'EOF'
# ==============================================================================
# SKHD CONFIG - AUTO-GENERATED BY UKE v6.1
# ==============================================================================
# DO NOT EDIT - Changes will be overwritten
# Edit config/registry.yaml and run: uke gen
# ==============================================================================

# ─────────────────────────────────────────────────────────────────────────────
# Smart Focus & Utilities
# ─────────────────────────────────────────────────────────────────────────────
cmd - escape : yabai -m window --focus mouse
alt - escape : /usr/bin/shortcuts run 'ToggleKeyboard'

# ─────────────────────────────────────────────────────────────────────────────
# Window Focus Navigation (PRIMARY: Cmd + hjkl)
# ─────────────────────────────────────────────────────────────────────────────
cmd - h : yabai -m window --focus west
cmd - j : yabai -m window --focus south
cmd - k : yabai -m window --focus north
cmd - l : yabai -m window --focus east

# ─────────────────────────────────────────────────────────────────────────────
# Window Movement (PRIMARY + SHIFT: Cmd+Shift + hjkl)
# ─────────────────────────────────────────────────────────────────────────────
cmd + shift - h : yabai -m window --warp west
cmd + shift - j : yabai -m window --warp south
cmd + shift - k : yabai -m window --warp north
cmd + shift - l : yabai -m window --warp east

# ─────────────────────────────────────────────────────────────────────────────
# Window Resizing (TERTIARY: Alt+Shift + hjkl)
# ─────────────────────────────────────────────────────────────────────────────
alt + shift - h : yabai -m window --resize left:-50:0
alt + shift - j : yabai -m window --resize bottom:0:50
alt + shift - k : yabai -m window --resize top:0:-50
alt + shift - l : yabai -m window --resize right:50:0

# ─────────────────────────────────────────────────────────────────────────────
# Launch Terminal
# ─────────────────────────────────────────────────────────────────────────────
cmd - return : open -a WezTerm

# ─────────────────────────────────────────────────────────────────────────────
# Window Controls
# ─────────────────────────────────────────────────────────────────────────────
cmd + shift - f : yabai -m window --toggle zoom-fullscreen
cmd + shift - space : yabai -m window --toggle float
cmd + shift - 0x2A : yabai -m window --toggle split

# ─────────────────────────────────────────────────────────────────────────────
# Advanced Layout Controls
# ─────────────────────────────────────────────────────────────────────────────
cmd + ctrl - s : yabai -m window --insert stack
cmd + shift - r : yabai -m space --rotate 90
cmd + shift - x : yabai -m space --mirror x-axis
cmd + shift - y : yabai -m space --mirror y-axis
cmd + shift - b : yabai -m space --balance
cmd + ctrl - t : yabai -m space --layout $(yabai -m query --spaces --space | jq -r 'if .type == "bsp" then "stack" else "bsp" end')

# ─────────────────────────────────────────────────────────────────────────────
# Workspace Navigation (PRIMARY + Number)
# ─────────────────────────────────────────────────────────────────────────────
cmd - 1 : yabai -m space --focus 1
cmd - 2 : yabai -m space --focus 2
cmd - 3 : yabai -m space --focus 3
cmd - 4 : yabai -m space --focus 4
cmd - 5 : yabai -m space --focus 5
cmd - 6 : yabai -m space --focus 6
cmd - 7 : yabai -m space --focus 7
cmd - 8 : yabai -m space --focus 8
cmd - 9 : yabai -m space --focus 9
cmd - 0x1D : yabai -m space --focus 10
cmd - 0x21 : yabai -m space --focus prev
cmd - 0x1E : yabai -m space --focus next

# ─────────────────────────────────────────────────────────────────────────────
# Move Window to Workspace (PRIMARY + SHIFT + Number)
# ─────────────────────────────────────────────────────────────────────────────
cmd + shift - 1 : yabai -m window --space 1 --focus
cmd + shift - 2 : yabai -m window --space 2 --focus
cmd + shift - 3 : yabai -m window --space 3 --focus
cmd + shift - 4 : yabai -m window --space 4 --focus
cmd + shift - 5 : yabai -m window --space 5 --focus
cmd + shift - 6 : yabai -m window --space 6 --focus
cmd + shift - 7 : yabai -m window --space 7 --focus
cmd + shift - 8 : yabai -m window --space 8 --focus
cmd + shift - 9 : yabai -m window --space 9 --focus
cmd + shift - 0x1D : yabai -m window --space 10 --focus

# ─────────────────────────────────────────────────────────────────────────────
# Gather Windows (Cmd + `)
# ─────────────────────────────────────────────────────────────────────────────
cmd - 0x32 : $HOME/.local/bin/uke-gather

# ─────────────────────────────────────────────────────────────────────────────
# Quick App Launchers (TERTIARY: Cmd+Alt)
# ─────────────────────────────────────────────────────────────────────────────
cmd + alt - b : open -a 'Brave Browser'
cmd + alt - o : open -a Obsidian
cmd + alt - c : open -a Code
cmd + alt - r : open -a Raindrop.io
cmd + alt - m : open -a Spotify
cmd + alt - t : open -a WezTerm

# ─────────────────────────────────────────────────────────────────────────────
# Bunches (BUNCH: Cmd+Ctrl)
# ─────────────────────────────────────────────────────────────────────────────
cmd + ctrl - 1 : $HOME/.local/bin/uke-bunch study
cmd + ctrl - 2 : $HOME/.local/bin/uke-bunch guitar
cmd + ctrl - 3 : $HOME/.local/bin/uke-bunch coding
cmd + ctrl - 4 : $HOME/.local/bin/uke-bunch email
cmd + ctrl - 5 : $HOME/.local/bin/uke-bunch reading
EOF

    ok "Generated: $out"
}

# ==============================================================================
# YABAI Generator
# ==============================================================================
gen_yabai() {
    local out="$UKE_GEN/yabai/yabairc"
    mkdir -p "$(dirname "$out")"
    
    log_info "Generating yabai config..."
    
    cat > "$out" << 'EOF'
#!/usr/bin/env sh
# ==============================================================================
# YABAI CONFIG - AUTO-GENERATED BY UKE v6.1
# ==============================================================================

# Load Scripting Addition
sudo yabai --load-sa

# ─────────────────────────────────────────────────────────────────────────────
# Layout Configuration (4px padding)
# ─────────────────────────────────────────────────────────────────────────────
yabai -m config layout bsp
yabai -m config window_placement second_child
yabai -m config top_padding    4
yabai -m config bottom_padding 4
yabai -m config left_padding   4
yabai -m config right_padding  4
yabai -m config window_gap     4

# ─────────────────────────────────────────────────────────────────────────────
# Mouse Configuration (click-to-focus)
# ─────────────────────────────────────────────────────────────────────────────
yabai -m config mouse_follows_focus off
yabai -m config focus_follows_mouse off
yabai -m config mouse_modifier alt
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize

# ─────────────────────────────────────────────────────────────────────────────
# Window Behavior
# ─────────────────────────────────────────────────────────────────────────────
yabai -m config split_ratio 0.50
yabai -m config auto_balance off

# ─────────────────────────────────────────────────────────────────────────────
# Window Borders (external borders utility)
# ─────────────────────────────────────────────────────────────────────────────
pkill -x borders 2>/dev/null || true
borders width=3 \
        active_color=0xff88c0d0 \
        inactive_color=0xff3b4252 &

# ─────────────────────────────────────────────────────────────────────────────
# Opacity
# ─────────────────────────────────────────────────────────────────────────────
yabai -m config window_opacity on
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.95

# ─────────────────────────────────────────────────────────────────────────────
# Exclusions - Apps That Should Float
# ─────────────────────────────────────────────────────────────────────────────
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^App Store$" manage=off
yabai -m rule --add app="^Karabiner" manage=off

# ==============================================================================
# WORKSPACE (SPACE) APP ASSIGNMENTS
# ==============================================================================

# Space 1: Browser
yabai -m rule --add app="^Safari$" space=^1
yabai -m rule --add app="^Brave Browser$" space=^1

# Space 2: Notes
yabai -m rule --add app="^Obsidian$" space=^2

# Space 3: Code
yabai -m rule --add app="^WezTerm$" space=^3
yabai -m rule --add app="^Code$" space=^3
yabai -m rule --add app="^Xcode$" space=^3

# Space 5: Documents
yabai -m rule --add app="^Preview$" space=^5
yabai -m rule --add app="^PDF Expert$" space=^5

# Space 6: Raindrop
yabai -m rule --add app="^Raindrop.io$" space=^6

# Space 7: Media
yabai -m rule --add app="^Spotify$" space=^7

# Space 8: Office
yabai -m rule --add app="^Microsoft Word$" space=^8
yabai -m rule --add app="^Microsoft Excel$" space=^8
yabai -m rule --add app="^Microsoft PowerPoint$" space=^8

# Space 9: Communication
yabai -m rule --add app="^Slack$" space=^9
yabai -m rule --add app="^Discord$" space=^9
yabai -m rule --add app="^Mail$" space=^9
yabai -m rule --add app="^Telegram$" space=^9
yabai -m rule --add app="^WhatsApp$" space=^9

# Space 10: AI
yabai -m rule --add app="^Claude$" space=^10
yabai -m rule --add app="^Perplexity$" space=^10

# ─────────────────────────────────────────────────────────────────────────────
# Catch-all: Everything else goes to Space 4
# ─────────────────────────────────────────────────────────────────────────────
yabai -m rule --add app!="^(Safari|Brave Browser|Obsidian|WezTerm|Code|Xcode|Preview|PDF Expert|Raindrop.io|Spotify|Microsoft Word|Microsoft Excel|Microsoft PowerPoint|Slack|Discord|Mail|Telegram|WhatsApp|Claude|Perplexity)$" space=^4

echo "yabai: Configuration loaded with workspace assignments"
EOF

    chmod +x "$out"
    ok "Generated: $out"
}

# ==============================================================================
# Hyprland Generator
# ==============================================================================
gen_hyprland() {
    local out="$UKE_GEN/hyprland/hyprland.conf"
    mkdir -p "$(dirname "$out")"
    
    log_info "Generating Hyprland config..."
    
    cat > "$out" << 'EOF'
# ==============================================================================
# HYPRLAND CONFIG - AUTO-GENERATED BY UKE v6.1
# ==============================================================================

monitor=,preferred,auto,1

input {
    kb_layout = de
    follow_mouse = 1
    sensitivity = 0
}

general {
    gaps_in = 4
    gaps_out = 8
    border_size = 2
    col.active_border = rgba(88c0d0ee) rgba(81a1c1ee) 45deg
    col.inactive_border = rgba(3b4252aa)
    layout = dwindle
}

decoration {
    rounding = 8
    blur {
        enabled = true
        size = 3
        passes = 1
    }
}

animations {
    enabled = true
    bezier = ease, 0.25, 0.1, 0.25, 1
    animation = windows, 1, 3, ease
    animation = fade, 1, 3, ease
    animation = workspaces, 1, 3, ease
}

dwindle {
    pseudotile = true
    preserve_split = true
}

# ==============================================================================
# Window Rules
# ==============================================================================
windowrulev2 = workspace 1, class:^(Brave-browser)$
windowrulev2 = workspace 2, class:^(obsidian)$
windowrulev2 = workspace 3, class:^(org.wezfurlong.wezterm)$
windowrulev2 = workspace 3, class:^(Code)$
windowrulev2 = workspace 5, class:^(org.gnome.Evince)$
windowrulev2 = workspace 6, class:^(Raindrop)$
windowrulev2 = workspace 7, class:^(Spotify)$
windowrulev2 = workspace 8, class:^(libreoffice-writer)$
windowrulev2 = workspace 8, class:^(libreoffice-calc)$
windowrulev2 = workspace 9, class:^(Slack)$
windowrulev2 = workspace 9, class:^(discord)$
windowrulev2 = workspace 9, class:^(thunderbird)$

# ==============================================================================
# Keybindings
# ==============================================================================

# Focus
bind = ALT, H, movefocus, l
bind = ALT, J, movefocus, d
bind = ALT, K, movefocus, u
bind = ALT, L, movefocus, r

# Move
bind = ALT SHIFT, H, movewindow, l
bind = ALT SHIFT, J, movewindow, d
bind = ALT SHIFT, K, movewindow, u
bind = ALT SHIFT, L, movewindow, r

# Resize
bind = SUPER SHIFT, H, resizeactive, -50 0
bind = SUPER SHIFT, J, resizeactive, 0 50
bind = SUPER SHIFT, K, resizeactive, 0 -50
bind = SUPER SHIFT, L, resizeactive, 50 0

# Workspaces
bind = ALT, 1, workspace, 1
bind = ALT, 2, workspace, 2
bind = ALT, 3, workspace, 3
bind = ALT, 4, workspace, 4
bind = ALT, 5, workspace, 5
bind = ALT, 6, workspace, 6
bind = ALT, 7, workspace, 7
bind = ALT, 8, workspace, 8
bind = ALT, 9, workspace, 9
bind = ALT, 0, workspace, 10

# Move to workspace
bind = ALT SHIFT, 1, movetoworkspace, 1
bind = ALT SHIFT, 2, movetoworkspace, 2
bind = ALT SHIFT, 3, movetoworkspace, 3
bind = ALT SHIFT, 4, movetoworkspace, 4
bind = ALT SHIFT, 5, movetoworkspace, 5
bind = ALT SHIFT, 6, movetoworkspace, 6
bind = ALT SHIFT, 7, movetoworkspace, 7
bind = ALT SHIFT, 8, movetoworkspace, 8
bind = ALT SHIFT, 9, movetoworkspace, 9
bind = ALT SHIFT, 0, movetoworkspace, 10

# Window controls
bind = ALT, Return, exec, wezterm
bind = ALT SHIFT, F, fullscreen, 0
bind = ALT SHIFT, Space, togglefloating

# Launchers
bind = ALT SUPER, B, exec, brave
bind = ALT SUPER, O, exec, obsidian
bind = ALT SUPER, C, exec, code
bind = ALT SUPER, M, exec, spotify
bind = ALT SUPER, Space, exec, wofi --show drun
bind = ALT SUPER, Q, killactive

# Gather & Bunches
bind = ALT, grave, exec, $HOME/.local/bin/uke-gather
bind = ALT CTRL, 1, exec, $HOME/.local/bin/uke-bunch study
bind = ALT CTRL, 2, exec, $HOME/.local/bin/uke-bunch guitar
bind = ALT CTRL, 3, exec, $HOME/.local/bin/uke-bunch coding
bind = ALT CTRL, 4, exec, $HOME/.local/bin/uke-bunch email
bind = ALT CTRL, 5, exec, $HOME/.local/bin/uke-bunch reading

# Mouse bindings
bindm = ALT, mouse:272, movewindow
bindm = ALT, mouse:273, resizewindow
EOF

    ok "Generated: $out"
}

# ==============================================================================
# Gather Script Generator
# ==============================================================================
gen_gather() {
    local out="$UKE_BIN/uke-gather"
    # Ensure bin directory exists
    mkdir -p "$(dirname "$out")"

    log_info "Generating uke-gather..."
    
    # Header
    cat > "$out" << 'HEADER'
#!/usr/bin/env bash
set -euo pipefail
# Resolve symlink to find true source location
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do
  DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
done
SCRIPT_DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
export UKE_ROOT="${SCRIPT_DIR%/bin}"
source "$UKE_ROOT/lib/core.sh"
require_cmd jq yq

gather_macos() {
    local current_space
    current_space=$(yabai -m query --spaces --space | jq -r '.index')
    log_info "Gathering windows for space $current_space..."
    
    case $current_space in
HEADER

    # Generate cases from registry.yaml
    for ws in $(yq -r '.workspaces | keys | .[]' "$UKE_CONFIG/registry.yaml"); do
        local apps=$(yq -r ".workspaces.${ws}.apps | .[]?" "$UKE_CONFIG/registry.yaml" 2>/dev/null)
        [[ -z "$apps" ]] && continue
        
        # Build selector
        local selector=""
        for app_key in $apps; do
            # Use select() instead of // empty for yq compatibility
            local app_name=$(yq -r ".apps.${app_key}.macos | select(. != null)" "$UKE_CONFIG/registry.yaml" 2>/dev/null)
            [[ -z "$app_name" ]] && continue
            [[ -n "$selector" ]] && selector="$selector or "
            selector="${selector}.app == \"$app_name\""
        done
        
        [[ -z "$selector" ]] && continue
        
        cat >> "$out" << EOF
        $ws)
            yabai -m query --windows | jq -r '.[] | select($selector) | .id' | \\
                xargs -I {} yabai -m window {} --space $ws 2>/dev/null || true
            ;;
EOF
    done
    
    # Footer
    cat >> "$out" << 'FOOTER'
        *)
            log_info "No gather action for space $current_space"
            ;;
    esac
    ok "Windows gathered for space $current_space"
}

gather_linux() {
    local current_space
    current_space=$(hyprctl activeworkspace | grep 'workspace ID' | awk '{print $3}')
    log_info "Gathering windows for Linux Workspace $current_space..."
    
    # Linux implementation logic (simplified stub for stability)
    log_warn "Linux gather logic is currently a stub in this version."
}

is_macos && gather_macos || gather_linux
FOOTER

    chmod +x "$out"
    ok "Generated: $out"
}

# ==============================================================================
# Main
# ==============================================================================
gen_all() {
    log_info "Generating all configs..."
    
    if is_macos; then
        gen_skhd
        gen_yabai
    else
        gen_hyprland
    fi
    
    gen_gather
    
    ok "All configs generated"
}

case "${1:-all}" in
    skhd)     gen_skhd ;;
    yabai)    gen_yabai ;;
    hyprland) gen_hyprland ;;
    gather)   gen_gather ;;
    all)      gen_all ;;
    *)        log_fatal "Unknown target: $1" ;;
esac
