#!/usr/bin/env bash
# ==============================================================================
# UKE Config Generator v6.3.2 - Arch Linux Ready (Fixed)
# ==============================================================================
set -euo pipefail
source "$(dirname "$0")/../lib/core.sh"

# ==============================================================================
# SKHD Generator (macOS only)
# ==============================================================================
gen_skhd() {
    local out="$UKE_GEN/skhd/skhdrc"
    mkdir -p "$(dirname "$out")"
    
    log_info "Generating skhd config..."
    
    cat > "$out" << 'EOF'
# ==============================================================================
# SKHD CONFIG - AUTO-GENERATED BY UKE
# ==============================================================================

# ─────────────────────────────────────────────────────────────────────────────
# Smart Focus & Utilities
# ─────────────────────────────────────────────────────────────────────────────
cmd - escape : yabai -m window --focus mouse
alt - escape : /usr/bin/shortcuts run 'ToggleKeyboard'

# ─────────────────────────────────────────────────────────────────────────────
# Window Focus Navigation (PRIMARY: Cmd + hjkl)
# ─────────────────────────────────────────────────────────────────────────────
cmd - h : yabai -m window --focus west
cmd - j : yabai -m window --focus south
cmd - k : yabai -m window --focus north
cmd - l : yabai -m window --focus east

# ─────────────────────────────────────────────────────────────────────────────
# Window Movement (PRIMARY + SHIFT: Cmd+Shift + hjkl)
# ─────────────────────────────────────────────────────────────────────────────
cmd + shift - h : yabai -m window --warp west
cmd + shift - j : yabai -m window --warp south
cmd + shift - k : yabai -m window --warp north
cmd + shift - l : yabai -m window --warp east

# ─────────────────────────────────────────────────────────────────────────────
# Window Resizing (TERTIARY: Alt+Shift + hjkl)
# ─────────────────────────────────────────────────────────────────────────────
alt + shift - h : yabai -m window --resize left:-50:0
alt + shift - j : yabai -m window --resize bottom:0:50
alt + shift - k : yabai -m window --resize top:0:-50
alt + shift - l : yabai -m window --resize right:50:0

# ─────────────────────────────────────────────────────────────────────────────
# Launch Terminal
# ─────────────────────────────────────────────────────────────────────────────
cmd - return : open -a WezTerm

# ─────────────────────────────────────────────────────────────────────────────
# Window Controls
# ─────────────────────────────────────────────────────────────────────────────
cmd + shift - f : yabai -m window --toggle zoom-fullscreen
cmd + shift - space : yabai -m window --toggle float
cmd + shift - 0x2A : yabai -m window --toggle split

# ─────────────────────────────────────────────────────────────────────────────
# Advanced Layout Controls
# ─────────────────────────────────────────────────────────────────────────────
cmd + ctrl - s : yabai -m window --insert stack
cmd + shift - r : yabai -m space --rotate 90
cmd + shift - x : yabai -m space --mirror x-axis
cmd + shift - y : yabai -m space --mirror y-axis
cmd + shift - b : yabai -m space --balance
cmd + ctrl - t : yabai -m space --layout $(yabai -m query --spaces --space | jq -r 'if .type == "bsp" then "stack" else "bsp" end')

# ─────────────────────────────────────────────────────────────────────────────
# Workspace Navigation (PRIMARY + Number)
# ─────────────────────────────────────────────────────────────────────────────
cmd - 1 : yabai -m space --focus 1
cmd - 2 : yabai -m space --focus 2
cmd - 3 : yabai -m space --focus 3
cmd - 4 : yabai -m space --focus 4
cmd - 5 : yabai -m space --focus 5
cmd - 6 : yabai -m space --focus 6
cmd - 7 : yabai -m space --focus 7
cmd - 8 : yabai -m space --focus 8
cmd - 9 : yabai -m space --focus 9
cmd - 0x1D : yabai -m space --focus 10
cmd - 0x21 : yabai -m space --focus prev
cmd - 0x1E : yabai -m space --focus next

# ─────────────────────────────────────────────────────────────────────────────
# Move Window to Workspace (PRIMARY + SHIFT + Number)
# ─────────────────────────────────────────────────────────────────────────────
cmd + shift - 1 : yabai -m window --space 1 --focus
cmd + shift - 2 : yabai -m window --space 2 --focus
cmd + shift - 3 : yabai -m window --space 3 --focus
cmd + shift - 4 : yabai -m window --space 4 --focus
cmd + shift - 5 : yabai -m window --space 5 --focus
cmd + shift - 6 : yabai -m window --space 6 --focus
cmd + shift - 7 : yabai -m window --space 7 --focus
cmd + shift - 8 : yabai -m window --space 8 --focus
cmd + shift - 9 : yabai -m window --space 9 --focus
cmd + shift - 0x1D : yabai -m window --space 10 --focus

# ─────────────────────────────────────────────────────────────────────────────
# Gather Windows (Cmd + `)
# ─────────────────────────────────────────────────────────────────────────────
cmd - 0x32 : $HOME/.local/bin/uke-gather

# ─────────────────────────────────────────────────────────────────────────────
# Quick App Launchers (TERTIARY: Cmd+Alt)
# ─────────────────────────────────────────────────────────────────────────────
cmd + alt - b : open -a 'Brave Browser'
cmd + alt - o : open -a Obsidian
cmd + alt - c : open -a Code
cmd + alt - r : open -a Raindrop.io
cmd + alt - m : open -a Spotify
cmd + alt - t : open -a WezTerm

# ─────────────────────────────────────────────────────────────────────────────
# Bunches (BUNCH: Cmd+Ctrl)
# ─────────────────────────────────────────────────────────────────────────────
cmd + ctrl - 1 : $HOME/.local/bin/uke-bunch study
cmd + ctrl - 2 : $HOME/.local/bin/uke-bunch guitar
cmd + ctrl - 3 : $HOME/.local/bin/uke-bunch coding
cmd + ctrl - 4 : $HOME/.local/bin/uke-bunch email
cmd + ctrl - 5 : $HOME/.local/bin/uke-bunch reading

# ─────────────────────────────────────────────────────────────────────────────
# Scratchpads
# ─────────────────────────────────────────────────────────────────────────────
cmd + shift - 0x32 : $HOME/.local/bin/uke-scratchpad terminal
cmd + alt - n : $HOME/.local/bin/uke-scratchpad notes

# ─────────────────────────────────────────────────────────────────────────────
# Session Management
# ─────────────────────────────────────────────────────────────────────────────
cmd + ctrl - s : $HOME/.local/bin/uke-session quick-save
cmd + ctrl + shift - s : $HOME/.local/bin/uke-session quick-restore
EOF

    chmod +x "$out"
    ok "Generated: $out"
}

# ==============================================================================
# Yabai Generator (macOS only)
# ==============================================================================
gen_yabai() {
    local out="$UKE_GEN/yabai/yabairc"
    mkdir -p "$(dirname "$out")"
    
    log_info "Generating yabai config..."
    
    cat > "$out" << 'EOF'
#!/usr/bin/env sh
# ==============================================================================
# YABAI CONFIG - AUTO-GENERATED BY UKE
# ==============================================================================

# Load Scripting Addition
sudo yabai --load-sa

# Layout Configuration
yabai -m config layout bsp
yabai -m config window_placement second_child
yabai -m config top_padding    4
yabai -m config bottom_padding 4
yabai -m config left_padding   4
yabai -m config right_padding  4
yabai -m config window_gap     4

# Mouse Configuration
yabai -m config mouse_follows_focus off
yabai -m config focus_follows_mouse off
yabai -m config mouse_modifier alt
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize

# Window Behavior
yabai -m config split_ratio 0.50
yabai -m config auto_balance off

# Window Borders
pkill -x borders 2>/dev/null || true
borders width=3 active_color=0xff88c0d0 inactive_color=0xff3b4252 &

# Opacity
yabai -m config window_opacity off
yabai -m rule --add app="^WezTerm$" opacity=0.92
yabai -m rule --add app="^Alacritty$" opacity=0.92
yabai -m rule --add app="^iTerm2$" opacity=0.92
yabai -m rule --add app="^Terminal$" opacity=0.95

# ==============================================================================
# WINDOW RULES
# ==============================================================================
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off sticky=on
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^App Store$" manage=off
yabai -m rule --add app="^Karabiner-Elements$" manage=off
yabai -m rule --add app="^Karabiner-EventViewer$" manage=off
yabai -m rule --add app="^zoom.us$" manage=off sticky=on opacity=1.0
yabai -m rule --add app="^FaceTime$" manage=off sticky=on
yabai -m rule --add title="Picture in Picture" manage=off sticky=on layer=above
yabai -m rule --add app="^Code$" title="Settings" manage=off
yabai -m rule --add title="Preferences" manage=off
yabai -m rule --add title="Settings" manage=off

# ==============================================================================
# WORKSPACE ASSIGNMENTS
# ==============================================================================
yabai -m rule --add app="^Safari$" space=^1
yabai -m rule --add app="^Brave Browser$" space=^1
yabai -m rule --add app="^Obsidian$" space=^2
yabai -m rule --add app="^WezTerm$" space=^3
yabai -m rule --add app="^Code$" space=^3
yabai -m rule --add app="^Xcode$" space=^3
yabai -m rule --add app="^Preview$" space=^5
yabai -m rule --add app="^PDF Expert$" space=^5
yabai -m rule --add app="^Raindrop.io$" space=^6
yabai -m rule --add app="^Spotify$" space=^7
yabai -m rule --add app="^Microsoft Word$" space=^8
yabai -m rule --add app="^Microsoft Excel$" space=^8
yabai -m rule --add app="^Microsoft PowerPoint$" space=^8
yabai -m rule --add app="^Slack$" space=^9
yabai -m rule --add app="^Discord$" space=^9
yabai -m rule --add app="^Mail$" space=^9
yabai -m rule --add app="^Telegram$" space=^9
yabai -m rule --add app="^WhatsApp$" space=^9
yabai -m rule --add app="^Claude$" space=^10
yabai -m rule --add app="^Perplexity$" space=^10

# Catch-all
yabai -m rule --add app!="^(Safari|Brave Browser|Obsidian|WezTerm|Code|Xcode|Preview|PDF Expert|Raindrop.io|Spotify|Microsoft Word|Microsoft Excel|Microsoft PowerPoint|Slack|Discord|Mail|Telegram|WhatsApp|Claude|Perplexity)$" space=^4

echo "yabai: Configuration loaded"
EOF

    chmod +x "$out"
    ok "Generated: $out"
}

# ==============================================================================
# Hyprland Generator (Linux) - FIXED v6.3.2
# ==============================================================================
gen_hyprland() {
    local out="$UKE_GEN/hyprland/hyprland.conf"
    mkdir -p "$(dirname "$out")"
    log_info "Generating Hyprland config..."
    
    cat > "$out" << 'EOF'
# ==============================================================================
# HYPRLAND CONFIG - AUTO-GENERATED BY UKE v6.3.2
# ==============================================================================

# MONITORS
monitor=,preferred,auto,1

# GENERAL SETTINGS
general {
    gaps_in = 2
    gaps_out = 4
    border_size = 2
    col.active_border = rgba(88c0d0ff)
    col.inactive_border = rgba(3b4252ff)
    layout = dwindle
    resize_on_border = true
}

# DECORATION
decoration {
    rounding = 4
    blur {
        enabled = true
        size = 6
        passes = 2
    }
    shadow {
        enabled = true
        range = 8
        color = rgba(1a1a1aee)
    }
}

# ANIMATIONS
animations {
    enabled = true
    bezier = easeOutQuint, 0.22, 1, 0.36, 1
    animation = windows, 1, 4, easeOutQuint, slide
    animation = border, 1, 10, default
    animation = fade, 1, 5, default
    animation = workspaces, 1, 4, easeOutQuint, slide
}

# INPUT
input {
    kb_layout = us
    follow_mouse = 1
    touchpad {
        natural_scroll = true
        tap-to-click = true
    }
}

gestures {
    workspace_swipe = true
    workspace_swipe_fingers = 3
}

dwindle {
    pseudotile = true
    preserve_split = true
}

misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
}

# ==============================================================================
# AUTOSTART & SYSTEM TRAY
# ==============================================================================
exec-once = waybar
exec-once = dunst
exec-once = hyprpaper
exec-once = nm-applet --indicator
exec-once = /usr/lib/polkit-kde-authentication-agent-1

# Clipboard (requires: cliphist wl-clipboard)
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# ==============================================================================
# QUALITY OF LIFE KEYBINDINGS
# ==============================================================================

# SPOTLIGHT (Wofi) - Alt + Super + Space
bind = ALT SUPER, space, exec, wofi --show drun --allow-images

# ZOOM (Accessibility for small screens) - Alt + Super + [=/-]
bind = ALT SUPER, equal, exec, hyprctl keyword cursor:zoom_factor 2.0
bind = ALT SUPER, minus, exec, hyprctl keyword cursor:zoom_factor 1.0

# CLIPBOARD HISTORY - Alt + V
bind = ALT, v, exec, cliphist list | wofi --dmenu | cliphist decode | wl-copy

# FILE MANAGER & SETTINGS
bind = ALT SUPER, f, exec, thunar
bind = ALT SUPER, s, exec, lxappearance

# ==============================================================================
# WINDOW MANAGEMENT KEYBINDINGS
# ==============================================================================

# Terminal & Basics
bind = ALT, return, exec, wezterm
bind = ALT, q, killactive
bind = ALT, escape, focuscurrentorlast

# Window Controls
bind = ALT SHIFT, f, fullscreen, 0
bind = ALT SHIFT, space, togglefloating
bind = ALT SHIFT, backslash, togglesplit

# Focus (Alt + hjkl)
bind = ALT, h, movefocus, l
bind = ALT, j, movefocus, d
bind = ALT, k, movefocus, u
bind = ALT, l, movefocus, r

# Move Window (Alt + Shift + hjkl)
bind = ALT SHIFT, h, movewindow, l
bind = ALT SHIFT, j, movewindow, d
bind = ALT SHIFT, k, movewindow, u
bind = ALT SHIFT, l, movewindow, r

# Resize Window (Super + Shift + hjkl)
bind = SUPER SHIFT, h, resizeactive, -50 0
bind = SUPER SHIFT, j, resizeactive, 0 50
bind = SUPER SHIFT, k, resizeactive, 0 -50
bind = SUPER SHIFT, l, resizeactive, 50 0

# ==============================================================================
# WORKSPACE NAVIGATION
# ==============================================================================

# Switch Workspace (Alt + 1-9, 0)
bind = ALT, 1, workspace, 1
bind = ALT, 2, workspace, 2
bind = ALT, 3, workspace, 3
bind = ALT, 4, workspace, 4
bind = ALT, 5, workspace, 5
bind = ALT, 6, workspace, 6
bind = ALT, 7, workspace, 7
bind = ALT, 8, workspace, 8
bind = ALT, 9, workspace, 9
bind = ALT, 0, workspace, 10
bind = ALT, bracketleft, workspace, e-1
bind = ALT, bracketright, workspace, e+1

# Move to Workspace (Alt + Shift + 1-9, 0)
bind = ALT SHIFT, 1, movetoworkspace, 1
bind = ALT SHIFT, 2, movetoworkspace, 2
bind = ALT SHIFT, 3, movetoworkspace, 3
bind = ALT SHIFT, 4, movetoworkspace, 4
bind = ALT SHIFT, 5, movetoworkspace, 5
bind = ALT SHIFT, 6, movetoworkspace, 6
bind = ALT SHIFT, 7, movetoworkspace, 7
bind = ALT SHIFT, 8, movetoworkspace, 8
bind = ALT SHIFT, 9, movetoworkspace, 9
bind = ALT SHIFT, 0, movetoworkspace, 10

# ==============================================================================
# UKE TOOLS
# ==============================================================================

# Gather Windows (Alt + `)
bind = ALT, grave, exec, $HOME/.local/bin/uke-gather

# App Launchers (Alt + Super + key)
bind = ALT SUPER, b, exec, brave
bind = ALT SUPER, o, exec, obsidian
bind = ALT SUPER, c, exec, code
bind = ALT SUPER, m, exec, spotify
bind = ALT SUPER, t, exec, wezterm

# Bunches (Alt + Ctrl + F1-F5)
bind = ALT CTRL, F1, exec, $HOME/.local/bin/uke-bunch study
bind = ALT CTRL, F2, exec, $HOME/.local/bin/uke-bunch guitar
bind = ALT CTRL, F3, exec, $HOME/.local/bin/uke-bunch coding
bind = ALT CTRL, F4, exec, $HOME/.local/bin/uke-bunch email
bind = ALT CTRL, F5, exec, $HOME/.local/bin/uke-bunch reading

# Scratchpads
bind = ALT SHIFT, grave, exec, $HOME/.local/bin/uke-scratchpad terminal
bind = ALT SUPER, n, exec, $HOME/.local/bin/uke-scratchpad notes

# Session Management
bind = ALT CTRL, s, exec, $HOME/.local/bin/uke-session quick-save
bind = ALT CTRL SHIFT, s, exec, $HOME/.local/bin/uke-session quick-restore

# ==============================================================================
# SCREENSHOT
# ==============================================================================
bind = , Print, exec, grim -g "$(slurp)" - | wl-copy
bind = SHIFT, Print, exec, grim - | wl-copy

# ==============================================================================
# MOUSE BINDINGS
# ==============================================================================
bindm = ALT, mouse:272, movewindow
bindm = ALT, mouse:273, resizewindow

# ==============================================================================
# WINDOW RULES
# ==============================================================================

# Float system/settings windows
windowrulev2 = float, class:^(pavucontrol)$
windowrulev2 = float, class:^(nm-connection-editor)$
windowrulev2 = float, class:^(lxappearance)$
windowrulev2 = float, class:^(blueman-manager)$
windowrulev2 = float, class:^(org.gnome.Calculator)$
windowrulev2 = float, class:^(thunar)$,title:^(File Operation Progress)$
windowrulev2 = float, title:^(Picture-in-Picture)$

# Terminal opacity
windowrulev2 = opacity 0.92 0.88, class:^(wezterm)$
windowrulev2 = opacity 0.92 0.88, class:^(Alacritty)$
windowrulev2 = opacity 0.92 0.88, class:^(kitty)$

# ==============================================================================
# WORKSPACE ASSIGNMENTS (Optional - uncomment to enable)
# ==============================================================================
# windowrulev2 = workspace 1, class:^(brave-browser)$
# windowrulev2 = workspace 1, class:^(firefox)$
# windowrulev2 = workspace 2, class:^(obsidian)$
# windowrulev2 = workspace 3, class:^(wezterm)$
# windowrulev2 = workspace 3, class:^(code)$
# windowrulev2 = workspace 7, class:^(spotify)$
# windowrulev2 = workspace 9, class:^(slack)$
# windowrulev2 = workspace 9, class:^(discord)$
EOF

    chmod +x "$out"
    ok "Generated: $out"
}

# ==============================================================================
# Gather Script Generator
# ==============================================================================
gen_gather() {
    local out="$UKE_BIN/uke-gather"
    mkdir -p "$(dirname "$out")"

    log_info "Generating uke-gather..."
    
    cat > "$out" << 'HEADER'
#!/usr/bin/env bash
set -euo pipefail

# Resolve symlink to find true source location
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do
  DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
done
SCRIPT_DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
export UKE_ROOT="${SCRIPT_DIR%/bin}"

source "$UKE_ROOT/lib/core.sh"
require_cmd jq

gather_macos() {
    local current_space
    current_space=$(yabai -m query --spaces --space | jq -r '.index')
    log_info "Gathering windows for space $current_space..."
    
    case $current_space in
        1)
            yabai -m query --windows | jq -r '.[] | select(.app == "Safari" or .app == "Brave Browser") | .id' | \
                xargs -I {} yabai -m window {} --space 1 2>/dev/null || true
            ;;
        2)
            yabai -m query --windows | jq -r '.[] | select(.app == "Obsidian") | .id' | \
                xargs -I {} yabai -m window {} --space 2 2>/dev/null || true
            ;;
        3)
            yabai -m query --windows | jq -r '.[] | select(.app == "WezTerm" or .app == "Code" or .app == "Xcode") | .id' | \
                xargs -I {} yabai -m window {} --space 3 2>/dev/null || true
            ;;
        5)
            yabai -m query --windows | jq -r '.[] | select(.app == "Preview" or .app == "PDF Expert") | .id' | \
                xargs -I {} yabai -m window {} --space 5 2>/dev/null || true
            ;;
        6)
            yabai -m query --windows | jq -r '.[] | select(.app == "Raindrop.io") | .id' | \
                xargs -I {} yabai -m window {} --space 6 2>/dev/null || true
            ;;
        7)
            yabai -m query --windows | jq -r '.[] | select(.app == "Spotify") | .id' | \
                xargs -I {} yabai -m window {} --space 7 2>/dev/null || true
            ;;
        8)
            yabai -m query --windows | jq -r '.[] | select(.app == "Microsoft Word" or .app == "Microsoft Excel" or .app == "Microsoft PowerPoint") | .id' | \
                xargs -I {} yabai -m window {} --space 8 2>/dev/null || true
            ;;
        9)
            yabai -m query --windows | jq -r '.[] | select(.app == "Slack" or .app == "Discord" or .app == "Mail") | .id' | \
                xargs -I {} yabai -m window {} --space 9 2>/dev/null || true
            ;;
        10)
            yabai -m query --windows | jq -r '.[] | select(.app == "Claude" or .app == "Perplexity") | .id' | \
                xargs -I {} yabai -m window {} --space 10 2>/dev/null || true
            ;;
        *)
            log_info "No gather action for space $current_space"
            ;;
    esac
    ok "Windows gathered"
}

gather_linux() {
    local current_ws
    current_ws=$(hyprctl activeworkspace -j | jq -r '.id')
    log_info "Gathering windows for workspace $current_ws..."
    
    case $current_ws in
        1)
            hyprctl clients -j | jq -r '.[] | select(.class | test("brave|firefox|chromium"; "i")) | .address' | \
                while read -r addr; do hyprctl dispatch movetoworkspacesilent "1,address:$addr" 2>/dev/null; done
            ;;
        2)
            hyprctl clients -j | jq -r '.[] | select(.class | test("obsidian"; "i")) | .address' | \
                while read -r addr; do hyprctl dispatch movetoworkspacesilent "2,address:$addr" 2>/dev/null; done
            ;;
        3)
            hyprctl clients -j | jq -r '.[] | select(.class | test("wezterm|code|alacritty|kitty"; "i")) | .address' | \
                while read -r addr; do hyprctl dispatch movetoworkspacesilent "3,address:$addr" 2>/dev/null; done
            ;;
        5)
            hyprctl clients -j | jq -r '.[] | select(.class | test("evince|zathura|okular"; "i")) | .address' | \
                while read -r addr; do hyprctl dispatch movetoworkspacesilent "5,address:$addr" 2>/dev/null; done
            ;;
        6)
            hyprctl clients -j | jq -r '.[] | select(.class | test("raindrop"; "i")) | .address' | \
                while read -r addr; do hyprctl dispatch movetoworkspacesilent "6,address:$addr" 2>/dev/null; done
            ;;
        7)
            hyprctl clients -j | jq -r '.[] | select(.class | test("spotify"; "i")) | .address' | \
                while read -r addr; do hyprctl dispatch movetoworkspacesilent "7,address:$addr" 2>/dev/null; done
            ;;
        8)
            hyprctl clients -j | jq -r '.[] | select(.class | test("libreoffice|soffice"; "i")) | .address' | \
                while read -r addr; do hyprctl dispatch movetoworkspacesilent "8,address:$addr" 2>/dev/null; done
            ;;
        9)
            hyprctl clients -j | jq -r '.[] | select(.class | test("slack|discord|thunderbird|telegram"; "i")) | .address' | \
                while read -r addr; do hyprctl dispatch movetoworkspacesilent "9,address:$addr" 2>/dev/null; done
            ;;
        10)
            hyprctl clients -j | jq -r '.[] | select(.class | test("claude"; "i")) | .address' | \
                while read -r addr; do hyprctl dispatch movetoworkspacesilent "10,address:$addr" 2>/dev/null; done
            ;;
        *)
            log_info "No gather action for workspace $current_ws"
            ;;
    esac
    ok "Windows gathered"
}

is_macos && gather_macos || gather_linux
HEADER

    chmod +x "$out"
    ok "Generated: $out"
}

# ==============================================================================
# Main
# ==============================================================================
gen_all() {
    log_info "Generating all configs..."
    if is_macos; then
        gen_skhd
        gen_yabai
    else
        gen_hyprland
    fi
    gen_gather
    ok "All configs generated"
}

case "${1:-all}" in
    skhd)     gen_skhd ;;
    yabai)    gen_yabai ;;
    hyprland) gen_hyprland ;;
    gather)   gen_gather ;;
    all)      gen_all ;;
    *)        log_fatal "Unknown target: $1" ;;
esac
