#!/usr/bin/env bash
# ==============================================================================
# UKE Config Generator
# ==============================================================================
set -euo pipefail
source "$(dirname "$0")/../lib/core.sh"

require_cmd yq

REGISTRY="$UKE_CONFIG/registry.yaml"

get_mod() {
    local name="$1" os="$2"
    yq -r ".modifiers.$name.$os // \"\"" "$REGISTRY"
}

gen_skhd() {
    local out="$UKE_GEN/skhd/skhdrc"
    mkdir -p "$(dirname "$out")"
    
    log_info "Generating skhd config..."
    
    cat > "$out" << 'HEADER'
# ==============================================================================
# SKHD CONFIG - AUTO-GENERATED BY UKE
# ==============================================================================
# DO NOT EDIT - Changes will be overwritten
# Edit config/registry.yaml and run: uke gen
# ==============================================================================

HEADER

    yq -r '.keys[] | select(.macos != null or .both != null) | 
        "\(.mod)|\(.key)|\(.macos // .both)"' "$REGISTRY" | while IFS='|' read -r mod key cmd; do
        
        local mod_str
        mod_str="$(get_mod "$mod" macos)"
        [[ -z "$mod_str" ]] && continue
        
        local key_str="$key"
        case "$key" in
            comma) key_str="0x2B" ;;
            period) key_str="0x2F" ;;
            "[") key_str="0x21" ;;
            "]") key_str="0x1E" ;;
            "\\") key_str="0x2A" ;;
            grave|"\`") key_str="0x32" ;;
            tab) key_str="0x30" ;;
            return) key_str="return" ;;
            escape) key_str="escape" ;;
            space) key_str="space" ;;
        esac
        
        echo "$mod_str - $key_str : $cmd"
    done >> "$out"
    
    ok "Generated: $out"
}

gen_yabai() {
    local out="$UKE_GEN/yabai/yabairc"
    mkdir -p "$(dirname "$out")"
    
    log_info "Generating yabai config..."
    
    cat > "$out" << 'HEADER'
#!/usr/bin/env bash
# ==============================================================================
# YABAI CONFIG - AUTO-GENERATED BY UKE
# ==============================================================================

yabai -m config layout bsp
yabai -m config window_placement second_child

yabai -m config top_padding    8
yabai -m config bottom_padding 8
yabai -m config left_padding   8
yabai -m config right_padding  8
yabai -m config window_gap     8

yabai -m config mouse_follows_focus on
yabai -m config mouse_modifier alt
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize

yabai -m config window_opacity on
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.95

# ==============================================================================
# Window Rules
# ==============================================================================
HEADER

    local all_apps=()
    
    for ws in $(yq -r '.workspaces | keys[]' "$REGISTRY"); do
        local apps
        apps=$(yq -r ".workspaces.$ws.apps // [] | .[]" "$REGISTRY" 2>/dev/null)
        
        for app in $apps; do
            local bundle
            bundle=$(yq -r ".apps.$app.macos // \"\"" "$REGISTRY")
            [[ -z "$bundle" ]] && continue
            
            local name="${bundle##*.}"
            [[ "$name" == "$bundle" ]] && name="$app"
            
            echo "yabai -m rule --add app=\"^.*${name}.*\$\" space=$ws"
            all_apps+=("$name")
        done
    done >> "$out"
    
    local catch_all_ws
    catch_all_ws=$(yq -r '.workspaces | to_entries[] | select(.value.catch_all == true) | .key' "$REGISTRY")
    
    if [[ -n "$catch_all_ws" && ${#all_apps[@]} -gt 0 ]]; then
        local pattern
        pattern=$(printf "%s|" "${all_apps[@]}")
        pattern="${pattern%|}"
        echo ""
        echo "# Catch-all rule"
        echo "yabai -m rule --add app!=\"^(${pattern})\$\" space=$catch_all_ws"
    fi >> "$out"
    
    cat >> "$out" << 'FOOTER'

# Float certain windows
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Karabiner" manage=off
FOOTER

    chmod +x "$out"
    ok "Generated: $out"
}

gen_hyprland() {
    local out="$UKE_GEN/hyprland/hyprland.conf"
    mkdir -p "$(dirname "$out")"
    
    log_info "Generating Hyprland config..."
    
    cat > "$out" << 'HEADER'
# ==============================================================================
# HYPRLAND CONFIG - AUTO-GENERATED BY UKE
# ==============================================================================

monitor=,preferred,auto,1

input {
    kb_layout = de
    follow_mouse = 1
    sensitivity = 0
}

general {
    gaps_in = 4
    gaps_out = 8
    border_size = 2
    col.active_border = rgba(89b4faee) rgba(cba6f7ee) 45deg
    col.inactive_border = rgba(45475aaa)
    layout = dwindle
}

decoration {
    rounding = 8
    blur {
        enabled = true
        size = 3
        passes = 1
    }
}

animations {
    enabled = true
    bezier = ease, 0.25, 0.1, 0.25, 1
    animation = windows, 1, 3, ease
    animation = fade, 1, 3, ease
    animation = workspaces, 1, 3, ease
}

dwindle {
    pseudotile = true
    preserve_split = true
}

# ==============================================================================
# Window Rules
# ==============================================================================
HEADER

    for ws in $(yq -r '.workspaces | keys[]' "$REGISTRY"); do
        local apps
        apps=$(yq -r ".workspaces.$ws.apps // [] | .[]" "$REGISTRY" 2>/dev/null)
        
        for app in $apps; do
            local class
            class=$(yq -r ".apps.$app.linux // \"\"" "$REGISTRY")
            [[ -z "$class" ]] && continue
            
            echo "windowrulev2 = workspace $ws, class:^(${class})$"
        done
    done >> "$out"
    
    echo "" >> "$out"
    echo "# ==============================================================================" >> "$out"
    echo "# Keybindings" >> "$out"
    echo "# ==============================================================================" >> "$out"

    yq -r '.keys[] | select(.linux != null or .both != null) | 
        "\(.mod)|\(.key)|\(.linux // .both)"' "$REGISTRY" | while IFS='|' read -r mod key cmd; do
        
        local mod_str
        mod_str="$(get_mod "$mod" linux)"
        [[ -z "$mod_str" ]] && continue
        
        local key_upper="${key^^}"
        case "$key" in
            comma) key_upper="comma" ;;
            period) key_upper="period" ;;
            "[") key_upper="bracketleft" ;;
            "]") key_upper="bracketright" ;;
            "\\") key_upper="backslash" ;;
            grave|"\`") key_upper="grave" ;;
            tab) key_upper="Tab" ;;
            return) key_upper="Return" ;;
            escape) key_upper="Escape" ;;
            space) key_upper="Space" ;;
            *) key_upper="${key^^}" ;;
        esac
        
        echo "bind = $mod_str, $key_upper, $cmd"
    done >> "$out"
    
    cat >> "$out" << 'FOOTER'

# Mouse bindings
bindm = ALT, mouse:272, movewindow
bindm = ALT, mouse:273, resizewindow
FOOTER

    ok "Generated: $out"
}

gen_all() {
    log_info "Generating all configs from registry..."
    
    if is_macos; then
        gen_skhd
        gen_yabai
    else
        gen_hyprland
    fi
    
    ok "All configs generated"
}

case "${1:-all}" in
    skhd)     gen_skhd ;;
    yabai)    gen_yabai ;;
    hyprland) gen_hyprland ;;
    all)      gen_all ;;
    *)        log_fatal "Unknown target: $1" ;;
esac
